### ISSUE TITLE
坪井さんのタスク

### ISSUE THREAD

**Issue by shiroi36** [shiroi36/REAL4#3]
1. 2023年11月20日報告書：[REAL4タスク報告書.pdf](https://github.com/shiroi36/REAL4/files/13406973/REAL4.pdf)
2. 2024年2月28日報告書：[REAL4タスク報告書_2024年2月28日.docx](https://github.com/shiroi36/REAL4/files/14431862/REAL4._2024.2.28.docx)
3. 2024年2月28日別紙資料（手順書）：[入力手順.docx](https://github.com/shiroi36/REAL4/files/14431864/default.docx)
4. [REAL4._2024.2.28_荒木追記.docx](https://github.com/shiroi36/REAL4/files/14433461/REAL4._2024.2.28_.docx)
5. 2024年3月6日報告書：
[REAL4タスク報告書_2024年3月5日.docx](https://github.com/shiroi36/REAL4/files/14507838/REAL4._2024.3.5.docx)
[REAL4タスク報告書_2024年3月5日.pdf](https://github.com/shiroi36/REAL4/files/14507842/REAL4._2024.3.5.pdf)
6. 2024年3月6日付録：
[入力手順.pdf](https://github.com/shiroi36/REAL4/files/14507847/default.pdf)
[入力手順.docx](https://github.com/shiroi36/REAL4/files/14507848/default.docx)
7. 2024年3月21日報告書：
[REAL4タスク報告書_2024年3月21日.pdf](https://github.com/shiroi36/REAL4/files/14692832/REAL4._2024.3.21.pdf)
[REAL4タスク報告書_2024年3月21日.docx](https://github.com/shiroi36/REAL4/files/14692833/REAL4._2024.3.21.docx)

~~~
営業見積(主材・PL・ボルト等構造一次部材)を素早く分析するツールとしての
REAL４を用いた活用が必要かと思われます。
その一方で、REAL4のライセンス数が少ないので、
昼間満足にREAL4に見積をさせると、
他の業務が回らないという問題があります。
以上から、たとえば簡単な構造スパン・断面を記したエクセルシートから、
夜間自動でREAL4が動いて積算出力を行う様なシステムを考えます。
このシステムでは、たとえば営業さんがエクセルシートを作成すれば、
大まかな荒明細が出てくることとなり、会社の思惑と一定しています。
~~~

- [x] どのような形式で見積を出力しているのか調査します。
- [x] REAL４のサポートに関して、メーカーのサポート窓口を調査します。
- [x] プログラム入力のマニュアル等があるのか調査します。
- [x] コマンドプロンプトから、そのプログラムを入力できるかどうかを調査します。
- [x] @shiroi36 と相談します。#7 がここだと最高
- [x] 講習会を受けます
> - [ ] ST-bridgeのインポートがどこまで信頼性があるか確認します。
> - [ ] ST-bridgeのコード？みたいのあれば勉強してみる。
- [x] やることを考えます
- [x] 羽生市倉庫を題材にモデル化・集計します。
> 以下は難しいらしい
> - [ ] 柱・梁のプログラム入力の方法を勉強します。
> - [ ] 柱脚のプログラム入力の方法を勉強します。
> - [ ] ダイアフラムガセット継手等プレートの入力の方法を勉強します。
> - [ ] どこまで積算がされていて、営業見積にどこまで耐えうるのかを検討します。
> - [ ] 以上ができればプログラムの検討にうつるので @shiroi36 と相談します。
- [x] CJ58のような1セットのWCS接合部を1つの特殊部品セットとして外部デバイスとやり取りできるか検討します。
- [x] 長孔の中心位置が作図できるか検討します。できない場合は、長孔ではなく通常のボルト穴を中心位置に作図します。
- [x] 報告書の構成を考えます。
> 1. 背景と目的
> 2. 過去物件のWCS入力例
> 3. WCSデータの受け渡し方法
> 4. 従来の情報伝達方法との比較
- [x] ファブリケータ向けの手順書を作成します。
- [x] 報告書をまとめます。

#### 2024年3月7日
- [x] 図・表にキャンプションを追加
- 1章
    - [x] タイトルを具体的に修正
    - [x] 図を追加
    - [x] 受講前の動機を示す
    - [x] パナソニックホームズのNS構法の記載を削除
- 3章
    - [x] 図を修正
    - [x] 提案手法の利点を追加
- 4章
    - [x] 当社→わが社

**Comment by KotaTsuboi** [comment]
- [ ] ユーザサポートとソフトダウンロードに必要なユーザ名とパスワードを確認する
